
name: Try to get forked commits
on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: getPrUrl
        id: pr-url
        uses: ammaratef45/pr-url-action@v1
      - name: display
        run: echo ${{ steps.pr-url.outputs.url }}
      - run: |
          echo '${{github.event.pull_request.head.repo.ssh_url}}'
          git checkout ${{ github.event.pull_request.base.sha }}
          git checkout ${{ github.event.pull_request.head.sha }}
